# Site settings
title: Qing's blog
motto: Scarcity means much
email: tsinggreen@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://1990q828j.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  1990q828j

# Build settings
markdown: kramdown
kramdown: 
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge
